[package]
name = "server"
version = "0.1.0"
authors = ["Noah Peeters <noah.peeters@icloud.com>"]

[dependencies]
libloading = "*"
glob = "*"

[dependencies.bots_lib]
path = "../bots_lib"
version = "*"
