[package]
name = "user1"
version = "0.1.0"
authors = ["Noah Peeters <noah.peeters@icloud.com>"]

[dependencies]

[dependencies.bots_lib]
path = "../bots_lib"
version = "*"

[lib]
name = "user1"
crate_type = ["dylib"]
